# Generated by Django 2.2.4 on 2020-12-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('photo', models.URLField(default='https://i.pinimg.com/originals/1b/59/c8/1b59c809d30e78e05a5f1794b33100c8.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('skill', models.CharField(default='beginner', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.URLField(default='https://i.pinimg.com/originals/1b/59/c8/1b59c809d30e78e05a5f1794b33100c8.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscle_group', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='main.User')),
                ('liked_by', models.ManyToManyField(related_name='liked_workouts', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Spotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(max_length=50)),
                ('workout_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.User')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='main.Gym')),
                ('user_name', models.ManyToManyField(related_name='spotters', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='members',
            field=models.ManyToManyField(related_name='gyms', to='main.User'),
        ),
    ]
