# Generated by Django 2.2.4 on 2020-12-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotter',
            name='skill',
            field=models.CharField(default='beginner', max_length=50),
        ),
    ]
