# Generated by Django 2.2.4 on 2020-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_spotter_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotter',
            name='about',
            field=models.TextField(default='my workout'),
        ),
    ]
