# Generated by Django 2.2.4 on 2020-12-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scale',
            field=models.IntegerField(default=1),
        ),
    ]
